### PR TITLE
Fixed ugly layer with a nice cobalt color

### PR DESCRIPTION
**Pull request by GitCodeBoi1654**
I fixed the issue of the ugly green layer color. 
I added a nice vs-code cobalt theme look to the layer selection.
Changed this file: src/airunner/pyqt/layer.ui

### CODE REVIEW

**Comment by w4ffl35** [comment]
The ticket was referring to the background color green of the selected layers as seen in this screen shot. I may have given you the wrong line number...

image

also the border color looks purple on my end not blue for some reason

**Review by w4ffl35 — CHANGES_REQUESTED** [review]
Thanks for picking up this ticket - please change the background color of the selected image. the border can change too, but the ticket was referencing the background color of the layer

this blue might be nice:

image

**Comment by GitCodeBoi1654** [comment]
ok

**Comment by GitCodeBoi1654** [comment]
i will put the rest on a new pull request

**Comment by GitCodeBoi1654** [comment]
ii will put the other code on a new pull request

**Pull request closed without merging**
