### PR TITLE
Fixed Issue #33

### PR DESCRIPTION
**Pull request by GitCodeBoi1654**
I got rid of the ugly green color and replaced it with a pleasing sky blue.

### CODE REVIEW

**Comment by GitCodeBoi1654** [comment]
huh why arent the changes going

**Comment by GitCodeBoi1654** [comment]
@w4ffl35 it workin now?

**Comment by GitCodeBoi1654** [comment]
@w4ffl35

**Review by w4ffl35 — COMMENTED** [review]
Awesome will look at this soon, just waking up 😁

**Comment by GitCodeBoi1654** [comment]
Oops there a typo lol

**Comment by GitCodeBoi1654** [comment]
Oh nvm my eyes are bad

**Comment by GitCodeBoi1654** [comment]
@w4ffl35 can it be merged yet

**Comment by w4ffl35** [comment]
I will merge this but a heads up that i am planning to move this into the user settings so that people can choose their own colors

**Pull request merged**
